In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("test.csv")
df = df.drop(["Unnamed: 0"], axis = 1)

In [3]:
df.head(50)

,MandatId,Statut,SurfaceMin,NombrePiecesEnum,NombreChambresEnum,TypeProjet,TypeBien,Region_LocalisationId,BudgetMaxEuro,CodePostal,Departement,dpt
0,2,7,0,5,2,1,1,16,280000,34000,Hérault,34
1,5,7,60,3,2,0,2,16,250000,34000,Hérault,34
2,78,7,90,4,3,1,1,16,500000,34000,Hérault,34
3,81,7,90,3,2,1,1,16,300000,34000,Hérault,34
4,1374,7,70,3,2,1,1,16,320000,34000,Hérault,34
5,1917,7,50,3,2,1,2,16,100000,34000,Hérault,34
6,2039,7,0,0,0,0,6,16,250000,34000,Hérault,34
7,2041,7,30,2,1,1,2,16,320000,34000,Hérault,34
8,2088,7,25,1,1,0,5,16,100000,34000,Hérault,34
9,2625,7,0,2,1,0,2,16,120000,34000,Hérault,34
10,3134,7,0,2,1,0,2,16,180000,34000,Hérault,34
11,3201,7,80,3,2,1,1,16,250000,34000,Hérault,34
12,3112,7,60,3,2,1,1,16,120000,34000,Hérault,34
13,3541,7,0,1,1,0,2,16,80000,34000,Hérault,34
14,4389,7,40,2,1,0,2,16,140000,34000,Hérault,34
15,4697,7,64,2,3,1,1,16,180000,34000,Hérault,34
16,4582,7,80,4,4,0,2,16,180000,34000,Hérault,34
17,4613,7,0,1,1,0,1,16,150000,34000,Hérault,34
18,4994,7,25,1,1,0,5,16,70000,34000,Hérault,34
19,6612,7,20,1,1,0,5,16,58000,34000,Hérault,34
20,6855,7,40,2,1,1,2,16,170000,34000,Hérault,34
21,7414,7,200,0,0,0,6,16,250000,34000,Hérault,34
22,7211,7,15,1,1,0,5,16,300000,34000,Hérault,34
23,7808,7,75,4,3,1,2,16,180000,34000,Hérault,34
24,8798,7,0,5,3,1,1,16,350000,34000,Hérault,34
25,8818,7,40,2,1,1,2,16,130000,34000,Hérault,34
26,1074,7,120,4,3,1,1,16,300000,34000,Hérault,34
27,9397,7,70,3,2,1,2,16,240000,34000,Hérault,34
28,10058,7,0,0,0,0,4,16,400000,34000,Hérault,34
29,13338,7,25,2,1,0,2,16,90000,34000,Hérault,34
30,13633,7,18,2,1,0,2,16,90000,34000,Hérault,34
31,13783,7,65,3,2,1,2,16,180000,34000,Hérault,34
32,27358,7,20,1,0,0,2,16,80000,34000,Hérault,34
33,27603,7,90,4,3,1,2,16,300000,34000,Hérault,34
34,27662,7,80,4,3,1,1,16,225000,34000,Hérault,34
35,27639,7,0,2,1,0,2,16,180000,34000,Hérault,34
36,28588,7,35,2,1,0,2,16,160000,34000,Hérault,34
37,29296,7,90,4,3,1,1,16,240000,34000,Hérault,34
38,29941,7,45,3,2,0,2,16,50000,34000,Hérault,34
39,30017,7,65,3,2,1,2,16,320000,34000,Hérault,34
40,30259,7,45,3,2,1,2,16,200000,34000,Hérault,34
41,29441,7,0,0,0,0,4,16,3000000,34000,Hérault,34
42,30247,7,12,1,0,0,2,16,60000,34000,Hérault,34
43,30303,7,60,3,2,0,2,16,240000,34000,Hérault,34
44,29616,7,45,2,1,1,7,16,150000,34000,Hérault,34
45,30278,7,15,1,0,0,2,16,92000,34000,Hérault,34
46,30158,7,25,1,0,0,2,16,150000,34000,Hérault,34
47,29179,7,40,2,1,0,2,16,180000,34000,Hérault,34
48,31121,7,60,3,2,2,2,16,215000,34000,Hérault,34
49,30969,7,20,1,1,0,2,16,80000,34000,Hérault,34

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 363 entries, 0 to 362
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   MandatId               363 non-null    int64
 1   Statut                 363 non-null    int64
 2   SurfaceMin             363 non-null    int64
 3   NombrePiecesEnum       363 non-null    int64
 4   NombreChambresEnum     363 non-null    int64
 5   TypeProjet             363 non-null    int64
 6   TypeBien               363 non-null    int64
 7   Region_LocalisationId  363 non-null    int64
 8   BudgetMaxEuro          363 non-null    int64
 9   CodePostal             363 non-null    int64
 10  Departement            363 non-null    object
 11  dpt                    363 non-null    int64
dtypes: int64(11), object(1)
memory usage: 34.2+ KB